version: '3'
services:
    neo4j:
        image: neo4j:latest
        ports:
            - "7474:7474"
            - "7687:7687"
        volumes:
          - ./neo4j/data:/data
          - .neo4j/logs:/logs
          - ./neo4j/import/:/var/lib/neo4j/import
          - .neo4j/plugins:/plugins
        environment:
          - NEO4J_AUTH=neo4j/test
          - NEO4J_dbms_default__listen__address=neo4j
          - NEO4J_dbms_default__advertised__address=neo4j
          - NEO4J_dbms_connector_bolt_listen__address=neo4j:7687
          - NEO4J_dbms_connector_http_listen__address=neo4j:7474
    python:
        build: ./python
        volumes:
          - ./python:/app
        ports:
          - "5000:5000"
        depends_on:
          - neo4j
          - corenlp
    corenlp:
        image: graham3333/corenlp-complete
        ports:
          - "9000:9000"
    web:
        depends_on:
          - database
        build: ./drupal
        ports:
          - "8080:80"
        volumes:
          - .:/app
    database:
        image: mysql:5.7
        command: --max_allowed_packet=32505856 #Set max_allowed_packet to 256M
        environment:
          MYSQL_DATABASE: jigsaw_navi
          MYSQL_ROOT_PASSWORD: jigsaw_navi
        ports:
          - "3306:3306"
        volumes:
          - jigsaw_navi_db:/var/lib/mysql
        restart: always
volumes:
    jigsaw_navi_db: